'use client';
import { useState } from 'react';
import Link from 'next/link';
import { UserAvatar } from '@/components/user-avatar';
import type { ListingType } from '@/types/database';
import { WhatsAppShareButton } from '@/components/whatsapp-share-button';
import { ListingPhoto } from '@/components/listing-photo';
import { getListingsForScope, type DiscoveryScope } from '@/app/feed/actions';
export type FeedListing = { id:string; user_id:string; type:ListingType; title:string; price:string|null; photo_url:string|null; seller_name:string; avatar_url:string|null; ward_name:string|null; ward_lga_name:string; vouch_count:number; trust_ratio:number };
type Sort = 'newest'|'price-asc'|'price-desc'|'trust';
const labels: Record<ListingType|'all', string> = { all:'All', sale:'Sale', service:'Service', request:'Request' };
function numericPrice(price:string|null) { if (!price) return null; const digits = price.replace(/[^0-9.]/g, ''); const value = Number(digits); return Number.isFinite(value) && value > 0 ? value : null; }
export function FeedList({ listings, currentUserId, postedListingId, discovery }: { listings:FeedListing[]; currentUserId:string; postedListingId:string|null; discovery:{lgaName:string;stateName:string;nearbyUsesWard:boolean} }) {
 const [category,setCategory]=useState<ListingType|'all'>('all'); const [scope,setScope]=useState<DiscoveryScope>('nearby'); const [sort,setSort]=useState<Sort>('newest'); const [scopeListings,setScopeListings]=useState(listings); const [loading,setLoading]=useState(false);
 async function changeScope(next:DiscoveryScope) { if(next===scope||loading) return; setLoading(true); try { setScopeListings(await getListingsForScope(next)); setScope(next); } finally { setLoading(false); } }
 const visible=scopeListings.filter(item=>category==='all'||item.type===category).sort((a,b)=> { if(sort==='trust') return Number(b.trust_ratio)-Number(a.trust_ratio); if(sort.startsWith('price')) { const ap=numericPrice(a.price), bp=numericPrice(b.price); if(ap===null&&bp===null)return 0;if(ap===null)return 1;if(bp===null)return -1; return sort==='price-asc'?ap-bp:bp-ap; } return 0; });
 const posted=postedListingId?listings.find(item=>item.id===postedListingId):undefined; const options=[['Nearby','nearby'],[discovery.lgaName,'lga'],[discovery.stateName,'state']] as const;
 return <div className="mx-auto max-w-7xl">{posted&&<section className="mb-4 rounded-xl bg-[#EFE7D6] p-4"><p className="font-semibold text-ink">Your listing is live.</p><WhatsAppShareButton id={posted.id} title={posted.title} price={posted.price} className="mt-3 bg-white" /></section>}<div className="grid grid-cols-1 gap-2 sm:grid-cols-3"><label className="text-xs font-semibold text-slate-600">Location<select value={scope} onChange={e=>void changeScope(e.target.value as DiscoveryScope)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-base text-ink"><>{options.map(([label,value])=><option key={value} value={value}>{label}</option>)}</></select></label><label className="text-xs font-semibold text-slate-600">Category<select value={category} onChange={e=>setCategory(e.target.value as ListingType|'all')} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-base text-ink">{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Sort<select value={sort} onChange={e=>setSort(e.target.value as Sort)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-base text-ink"><option value="newest">Newest first</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="trust">Trust: highest first</option></select></label></div><section className="mt-6 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3" aria-live="polite">{loading?<Empty>Loading listings…</Empty>:visible.length?visible.map(listing=><ListingCard key={listing.id} listing={listing} currentUserId={currentUserId} showWideLocation={scope!=='nearby'}/>):<Empty>No {category==='all'?'':labels[category].toLowerCase()} listings yet.</Empty>}</section></div>;
}
function Empty({children}:{children:React.ReactNode}) { return <div className="col-span-full rounded-2xl bg-white p-8 text-center text-sm text-slate-500 ring-1 ring-slate-200">{children}</div>; }
function ListingCard({listing,currentUserId,showWideLocation}:{listing:FeedListing;currentUserId:string;showWideLocation:boolean}) { const percentage=Number(listing.trust_ratio)*100; const label=listing.type==='sale'?'For sale':listing.type==='service'?'Service':'Request'; return <article className="flex flex-col justify-between rounded-2xl bg-white p-5 shadow-xs ring-1 ring-slate-200"><div><ListingPhoto photoUrl={listing.photo_url} type={listing.type} title={listing.title}/><p className="mt-4 text-xs font-bold uppercase tracking-wider text-brick">{label}</p><h2 className="mt-1.5 font-heading text-lg font-bold text-ink line-clamp-2"><Link href={`/listings/${listing.id}`}>{listing.title}</Link></h2><p className="mt-1 font-semibold text-adire">{listing.type==='request'||!listing.price?'Looking to buy':listing.price}</p></div><div className="mt-4 flex items-center gap-3 border-t border-[#EFE7D6] pt-4"><TrustRing id={listing.user_id} name={listing.seller_name} avatarUrl={listing.avatar_url??undefined} percentage={percentage} currentUserId={currentUserId}/><Link href={listing.user_id===currentUserId?'/profile':`/sellers/${listing.user_id}`} className="min-w-0 flex-1"><p className="truncate font-semibold text-ink">{listing.seller_name}</p><p className="truncate text-xs text-slate-500">{showWideLocation?listing.ward_lga_name:listing.ward_name??''}</p></Link><span className="font-mono text-sm font-semibold text-adire">{Math.round(percentage)}%</span></div></article>; }
export function TrustRing({id,name,avatarUrl,percentage,currentUserId,animate=false}:{id:string;name:string;avatarUrl?:string;percentage:number;currentUserId?:string;animate?:boolean}) { const href=currentUserId?(id===currentUserId?'/profile':`/sellers/${id}`):`/sellers/${id}`; return <Link href={href}><div aria-label={`${Math.round(percentage)}% neighbour trust`} className={`grid h-11 w-11 shrink-0 place-items-center rounded-full ${animate?'animate-success-pop':''}`} style={{background:`conic-gradient(#D9A441 ${percentage*3.6}deg, #EFE7D6 0deg)`}}><div className="grid h-8 w-8 place-items-center rounded-full bg-paper"><UserAvatar id={id} name={name} avatarUrl={avatarUrl} className="h-7 w-7 text-xs"/></div></div></Link>; }
