'use client';
import { useMemo, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { onboardingProfileSchema } from '@/lib/validation';

type State = { id: string; name: string }; type Lga = { id: string; state_id: string; name: string }; type Ward = { id: string; lga_id: string; name: string };
export function OnboardingForm({ states, lgas, wards }: { states: State[]; lgas: Lga[]; wards: Ward[] }) {
 const router = useRouter(); const [name,setName]=useState(''); const [stateId,setStateId]=useState(''); const [lgaId,setLgaId]=useState(''); const [wardId,setWardId]=useState(''); const [phone,setPhone]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const availableLgas=useMemo(()=>lgas.filter((l)=>l.state_id===stateId),[lgas,stateId]); const availableWards=useMemo(()=>wards.filter((w)=>w.lga_id===lgaId),[wards,lgaId]); const hasWardData=availableWards.length>0;
 async function submit(event: FormEvent) { event.preventDefault(); setError(''); const validated=onboardingProfileSchema.safeParse({name,lgaId,wardId:wardId||undefined,phone:phone.trim()||undefined}); if(!validated.success||!stateId||!lgaId||(hasWardData&&!wardId)){setError(hasWardData?'Enter your name, then choose a State, Local Government, and Ward.':'Enter your name, State, and Local Government.');return;} setLoading(true); try { const response=await fetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(validated.data)}); const payload=await response.json().catch(()=>({})); if(!response.ok){setError(payload.error??'We could not save your details. Please try again.');return;} router.replace('/feed');router.refresh(); } catch(err){console.error('Onboarding request failed:',err);setError('Connection issue — check your network and try again.');} finally {setLoading(false);} }
 return <main className="mx-auto flex min-h-screen max-w-md items-center px-4 py-8"><section className="w-full rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="font-heading text-sm font-bold uppercase tracking-[0.18em] text-adire">Kobo Circle</p><h1 className="mt-3 font-heading text-3xl font-bold text-ink">Join your local community</h1><p className="mt-2 text-sm leading-6 text-slate-600">Tell neighbours where to find you. Add your phone so buyers can reach you on WhatsApp, or skip it for now.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-semibold">Your name<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name" maxLength={60} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-3 text-base" /></label><label className="block text-sm font-semibold">State<select required value={stateId} onChange={e=>{setStateId(e.target.value);setLgaId('');setWardId('');}} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-3 text-base"><option value="">Choose your State</option>{states.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="block text-sm font-semibold">Local Government<select required disabled={!stateId} value={lgaId} onChange={e=>{setLgaId(e.target.value);setWardId('');}} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-3 text-base disabled:bg-slate-100"><option value="">Choose your Local Government</option>{availableLgas.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{lgaId&&hasWardData?<label className="block text-sm font-semibold">Ward<select required value={wardId} onChange={e=>setWardId(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-3 text-base"><option value="">Choose your Ward</option>{availableWards.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>:lgaId?<p className="text-sm text-slate-600">Ward-level data isn&apos;t available for this area yet — you can still join using your Local Government Area.</p>:null}<label className="block text-sm font-semibold">Phone number <span className="font-normal text-slate-500">(optional)</span><input value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" inputMode="tel" maxLength={20} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-3 text-base" /></label><button disabled={loading||!states.length} className="w-full rounded-lg bg-adire px-4 py-3 font-semibold text-white disabled:opacity-60">{loading?'Saving…':'Continue to Kobo Circle'}</button></form>{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}</section></main>;
}
